### ISSUE TITLE
Medusa won't start

### ISSUE THREAD

**Issue by steveschow** [ArieKindicator/ReadyNAS#3]
I tried to install onto ReadyNAS using the provided medusa.deb package.  It seemed to install it fine with no error messages.

However it will not start, it produces error.

I tried to manually start it using SSH, but I get the following errors:

```
Traceback (most recent call last):
  File "/apps/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/apps/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/apps/medusa/medusa/init/__init__.py", line 23, in initialize
    _monkey_patch_fs_functions()
  File "/apps/medusa/medusa/init/__init__.py", line 94, in _monkey_patch_fs_functions
    from medusa.init import filesystem
  File "/apps/medusa/medusa/init/filesystem.py", line 12, in <module>
    from builtins import map
ImportError: No module named builtins
```

Sounds like there must be some manual steps I need to do in order to get python2 ready for builtins?  ANY HELP APPRECIATED.

**Comment by steveschow** [comment]
python is version 2.7.16

**Comment by steveschow** [comment]
duplicate issue, deleting
